In [1]:
# Libraries
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas as pd
import numpy as np
import re
from datetime import datetime as dt

In [141]:
# Importing Netflix DF
netflix = pd.read_csv("../data/Netflix_Titles.csv", )
netflix = netflix.drop(columns=["show_id", "description"])
netflix["date_added"] = pd.to_datetime(netflix["date_added"])
netflix["date_added"] = netflix["date_added"].dt.strftime("%Y-%m")

# Importing IMDB DF
IMDB = pd.read_csv("../data/IMDb_results_nov-22-2020.csv", index_col=0)

# Joinig both tables
netflix = netflix.join(IMDB)

# Cleaning the DF mantaining the desired columns
netflix = netflix.drop(columns=["IMDB_titleID", "IMDB_title_name"])
netflix = netflix.rename(columns={"IMDB_rating":"IMDb_rating"})

In [142]:
netflix

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDb_rating
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",3.2 based on 294 user ratings
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016-09,2016,TV-MA,94 min,Stand-Up Comedy,5.0 based on 21 user ratings
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09,2013,TV-Y7-FV,1 Season,Kids' TV,"7.9 based on 5,331 user ratings"
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09,2016,TV-Y7,1 Season,Kids' TV,6.0 based on 830 user ratings
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09,2017,TV-14,99 min,Comedies,"5.2 based on 5,496 user ratings"
...,...,...,...,...,...,...,...,...,...,...,...
6229,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","8.3 based on 8,840 user ratings"
6230,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"7.7 based on 4,530 user ratings"
6231,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,6.1 based on 19 user ratings
6232,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","7.9 based on 14,452 user ratings"
6233,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies","8.9 based on 802,016 user ratings"

##### MANERA PARA ENCONTRAR TODAS LAS VECES QUE SALE UN PAÍS

Done

In [98]:
netflix_test_usa = netflix[netflix["country"].str.contains("United States", case=False, regex=False, na=False)]

In [99]:
netflix_test_usa

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDB_rating
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",3.2 based on 294 user ratings
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09,2013,TV-Y7-FV,1 Season,Kids' TV,"7.9 based on 5,331 user ratings"
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09,2016,TV-Y7,1 Season,Kids' TV,6.0 based on 830 user ratings
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09,2017,TV-14,99 min,Comedies,"5.2 based on 5,496 user ratings"
6,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada",2017-09,2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","6.1 based on 53,988 user ratings"
...,...,...,...,...,...,...,...,...,...,...,...
6225,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies","8.0 based on 72,555 user ratings"
6226,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...",7.7 based on 777 user ratings
6229,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","8.3 based on 8,840 user ratings"
6230,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"7.7 based on 4,530 user ratings"
6233,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies","8.9 based on 802,016 user ratings"

In [100]:
usa_testing = []

for word in netflix_test_usa["country"]:
    usa_testing.extend(re.findall(r"\bUnited States*", word))

In [101]:
len(usa_testing)

2610

##### INTENTO DE OBTENER TODOS LOS PAÍSES DE MANERA ÚNICA

Done

In [102]:
#Obtención de todos los unique values. Ahora extracción de los mismos en otra cell
countries = list(netflix["country"].apply(str).unique())
countries = [x for x in countries if x != "nan"]
#len(countries) es 554

In [103]:
only_first_country = []

for country in countries:
    only_first_country.extend(re.findall(r"^(.+?),", country))

In [104]:
countries_clean = list(set(only_first_country))
countries_clean.sort()
print(countries_clean)
len(countries_clean)

['Argentina', 'Australia', 'Austria', 'Belgium', 'Brazil', 'Bulgaria', 'Cambodia', 'Canada', 'Chile', 'China', 'Colombia', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Egypt', 'Finland', 'France', 'Georgia', 'Germany', 'Ghana', 'Hong Kong', 'Iceland', 'India', 'Indonesia', 'Iran', 'Ireland', 'Israel', 'Italy', 'Japan', 'Lebanon', 'Malaysia', 'Mauritius', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Pakistan', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia', 'Saudi Arabia', 'Serbia', 'Singapore', 'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'Soviet Union', 'Spain', 'Sweden', 'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Venezuela']

64

##### OBTENCIÓN TODOS LOS GÉNEROS

Done

In [105]:
genres = netflix["listed_in"].apply(str).unique()
genres = [x for x in genres if x != "nan"]
#len(genres) de 461

In [106]:
only_first_genre = []

for genre in genres:
    only_first_genre.extend(re.findall(r"^(.+?),", genre))

In [107]:
genre_clean = list(set(only_first_genre))
genre_clean.sort()
print(genre_clean)
len(genre_clean)

['Action & Adventure', 'Anime Features', 'Anime Series', 'British TV Shows', 'Children & Family Movies', 'Classic & Cult TV', 'Classic Movies', 'Comedies', 'Crime TV Shows', 'Cult Movies', 'Documentaries', 'Docuseries', 'Dramas', 'Horror Movies', 'Independent Movies', 'International Movies', 'International TV Shows', "Kids' TV", 'Music & Musicals', 'Reality TV', 'Romantic TV Shows', 'Sci-Fi & Fantasy', 'Spanish-Language TV Shows', 'Stand-Up Comedy & Talk Shows', 'TV Action & Adventure', 'TV Comedies', 'TV Dramas', 'TV Horror', 'TV Sci-Fi & Fantasy']

29

#### Release Year

Done

In [108]:
# Obtener todos los valores y hacer un sort de manera descendente. 
# Ver aquellas fechas que tienen una mayor presencia (pelis/series nuevas vs antiguas)
# Agrupar por bins para categorizar

release = list(netflix["release_year"].apply(int).unique())
release.sort()
print(release)

[1925, 1942, 1943, 1944, 1945, 1946, 1947, 1954, 1955, 1956, 1958, 1959, 1960, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

##### One Hot Encoding

In [109]:
#PASO 1
netflix[netflix["country"].str.contains("United States", case=False, regex=False, na=False)]

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDB_rating
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",3.2 based on 294 user ratings
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09,2013,TV-Y7-FV,1 Season,Kids' TV,"7.9 based on 5,331 user ratings"
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09,2016,TV-Y7,1 Season,Kids' TV,6.0 based on 830 user ratings
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09,2017,TV-14,99 min,Comedies,"5.2 based on 5,496 user ratings"
6,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada",2017-09,2014,R,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","6.1 based on 53,988 user ratings"
...,...,...,...,...,...,...,...,...,...,...,...
6225,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies","8.0 based on 72,555 user ratings"
6226,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...",7.7 based on 777 user ratings
6229,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","8.3 based on 8,840 user ratings"
6230,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"7.7 based on 4,530 user ratings"
6233,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies","8.9 based on 802,016 user ratings"

In [110]:
# PASO 2
netflix_test_usa[["listed_in"]].unstack().str.get_dummies(sep=", ").sum(level = 0).rename(index={"listed_in":"United States"})

,Action & Adventure,Anime Features,Anime Series,British TV Shows,Children & Family Movies,Classic & Cult TV,Classic Movies,Comedies,Crime TV Shows,Cult Movies,...,TV Action & Adventure,TV Comedies,TV Dramas,TV Horror,TV Mysteries,TV Sci-Fi & Fantasy,TV Shows,TV Thrillers,Teen TV Shows,Thrillers
United States,247,3,9,22,258,16,61,447,115,37,...,73,195,189,30,44,50,3,23,20,202

In [17]:
# Hay que sustituir la parte de "United States" por country a la hora de hacer un for loop

In [111]:
#ESTO FUNCIONA PARA UN PAÍS, REPLICARLO PARA MÁS
def dummy_country_genre(df, country):
    country_1 = df[df["country"].str.contains(country, case=False, regex=False, na=False)]
    
    return country_1[["listed_in"]].unstack().str.get_dummies(sep=", ").sum(level = 0).rename(index={"listed_in":country})

dummy_country_genre(netflix, "United States")

,Action & Adventure,Anime Features,Anime Series,British TV Shows,Children & Family Movies,Classic & Cult TV,Classic Movies,Comedies,Crime TV Shows,Cult Movies,...,TV Action & Adventure,TV Comedies,TV Dramas,TV Horror,TV Mysteries,TV Sci-Fi & Fantasy,TV Shows,TV Thrillers,Teen TV Shows,Thrillers
United States,247,3,9,22,258,16,61,447,115,37,...,73,195,189,30,44,50,3,23,20,202

In [112]:
def dummy_country_genre_test2(df, country):
    
    """
    Input: Dataframe, list of unique countries
    
    Output: The function returns a SUM one-hot encoded of the genres that appear per country
    """
    
    list_of = []
    for c in country:
        country_1 = df[df["country"].str.contains(c, case=False, regex=False, na=False)]
        df2 = country_1[["listed_in"]].unstack().str.get_dummies(sep=", ").sum(level = 0).rename(index={"listed_in":c})
        list_of.append(df2)
          
    result = pd.concat(list_of).fillna(0).astype(int)
    
    return result

dummy_country_genre_test2(netflix, countries_clean)

,Action & Adventure,Children & Family Movies,Classic Movies,Comedies,Crime TV Shows,Cult Movies,Documentaries,Docuseries,Dramas,Horror Movies,...,TV Action & Adventure,TV Mysteries,TV Sci-Fi & Fantasy,TV Thrillers,Stand-Up Comedy & Talk Shows,Anime Series,Classic & Cult TV,Korean TV Shows,Anime Features,TV Shows
Argentina,3,2,1,10,4,1,6,1,27,3,...,0,0,0,0,0,0,0,0,0,0
Australia,10,16,3,14,8,1,14,9,29,3,...,1,1,2,2,0,0,0,0,0,0
Austria,0,0,0,0,0,0,3,0,5,0,...,0,0,0,0,0,0,0,0,0,0
Belgium,9,4,0,13,6,1,5,0,33,4,...,1,1,1,0,0,0,0,0,0,0
Brazil,3,3,0,11,4,0,11,2,22,0,...,0,1,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
United Arab Emirates,3,3,0,5,1,0,4,0,10,1,...,0,0,0,0,0,0,0,0,0,0
United Kingdom,59,24,11,67,43,5,106,82,122,22,...,6,3,3,3,1,0,6,0,0,0
United States,247,258,61,447,115,37,401,134,533,145,...,73,44,50,23,27,9,16,2,3,3
Uruguay,0,0,0,1,0,0,5,0,4,0,...,0,0,0,0,0,0,0,0,0,0
Venezuela,0,0,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
countries_genre_encoded = dummy_country_genre_test2(netflix, countries_clean)
#countries_genre_encoded.to_csv("../data/contry_genre_encoded.csv")

### Test Merge con DF de Plataformas de Streaming

In [113]:
netflix_test_merge = netflix

In [114]:
netflix_test_merge.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDB_rating
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",3.2 based on 294 user ratings
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016-09,2016,TV-MA,94 min,Stand-Up Comedy,5.0 based on 21 user ratings
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09,2013,TV-Y7-FV,1 Season,Kids' TV,"7.9 based on 5,331 user ratings"
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09,2016,TV-Y7,1 Season,Kids' TV,6.0 based on 830 user ratings
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09,2017,TV-14,99 min,Comedies,"5.2 based on 5,496 user ratings"

In [115]:
streaming_platforms_movies = pd.read_csv("../data/StreamingPlatforms_Movies.csv", index_col=0)
streaming_platforms_movies = streaming_platforms_movies.drop(columns=["Language", "Runtime", "Directors", "Genres", "Type", "IMDb", "Rotten Tomatoes", "ID", "Country"])
streaming_platforms_movies.head()

,Title,Year,Age,Netflix,Hulu,Prime Video,Disney+
0,Inception,2010,13+,1,0,0,0
1,The Matrix,1999,18+,1,0,0,0
2,Avengers: Infinity War,2018,13+,1,0,0,0
3,Back to the Future,1985,7+,1,0,0,0
4,"The Good, the Bad and the Ugly",1966,18+,1,0,1,0

In [116]:
streaming_platforms_series = pd.read_csv("../data/StreamingPlatforms_TV_Shows.csv", index_col=0)
streaming_platforms_series = streaming_platforms_series.drop(columns=["IMDb", "Rotten Tomatoes", "type"])
streaming_platforms_series.head()

              Title  Year  Age  Netflix  Hulu  Prime Video  Disney+
0      Breaking Bad  2008  18+        1     0            0        0
1   Stranger Things  2016  16+        1     0            0        0
2       Money Heist  2017  18+        1     0            0        0
3          Sherlock  2010  16+        1     0            0        0
4  Better Call Saul  2015  18+        1     0            0        0

In [36]:
netflix_test_merge.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDB_rating
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",3.2 based on 294 user ratings
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016-09,2016,TV-MA,94 min,Stand-Up Comedy,5.0 based on 21 user ratings
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09,2013,TV-Y7-FV,1 Season,Kids' TV,"7.9 based on 5,331 user ratings"
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09,2016,TV-Y7,1 Season,Kids' TV,6.0 based on 830 user ratings
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09,2017,TV-14,99 min,Comedies,"5.2 based on 5,496 user ratings"

In [117]:
full_netflix = pd.concat([streaming_platforms_movies, streaming_platforms_series])
full_netflix = full_netflix.reset_index(drop=True)
full_netflix = full_netflix.rename(columns={"Title":"title", "Year":"year", "Age":"age"})

In [118]:
full_netflix.head()

,title,year,age,Netflix,Hulu,Prime Video,Disney+
0,Inception,2010,13+,1,0,0,0
1,The Matrix,1999,18+,1,0,0,0
2,Avengers: Infinity War,2018,13+,1,0,0,0
3,Back to the Future,1985,7+,1,0,0,0
4,"The Good, the Bad and the Ugly",1966,18+,1,0,1,0

In [119]:
netflix_test_merge = pd.merge(netflix_test_merge, full_netflix, on="title", how="left")

In [120]:
netflix_test_merge

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDB_rating,year,age,Netflix,Hulu,Prime Video,Disney+
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",3.2 based on 294 user ratings,2019.0,NaN,1.0,0.0,0.0,0.0
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016-09,2016,TV-MA,94 min,Stand-Up Comedy,5.0 based on 21 user ratings,NaN,NaN,NaN,NaN,NaN,NaN
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09,2013,TV-Y7-FV,1 Season,Kids' TV,"7.9 based on 5,331 user ratings",NaN,NaN,NaN,NaN,NaN,NaN
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09,2016,TV-Y7,1 Season,Kids' TV,6.0 based on 830 user ratings,NaN,NaN,NaN,NaN,NaN,NaN
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09,2017,TV-14,99 min,Comedies,"5.2 based on 5,496 user ratings",2017.0,NaN,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6248,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","8.3 based on 8,840 user ratings",2003.0,NaN,1.0,0.0,0.0,0.0
6249,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"7.7 based on 4,530 user ratings",NaN,NaN,NaN,NaN,NaN,NaN
6250,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,NaN,60 min,Movies,6.1 based on 19 user ratings,NaN,NaN,NaN,NaN,NaN,NaN
6251,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","7.9 based on 14,452 user ratings",NaN,NaN,NaN,NaN,NaN,NaN
6252,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies","8.9 based on 802,016 user ratings",1971.0,18+,0.0,0.0,1.0,0.0

In [126]:
netflix_test_merge[netflix_test_merge["year"] > 0].tail(25)

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDB_rating,year,age,Netflix,Hulu,Prime Video,Disney+
6211,TV Show,Kim's Convenience,NaN,"Paul Sun-Hyung Lee, Jean Yoon, Andrea Bang, Si...",Canada,2019-04,2019,TV-14,3 Seasons,TV Comedies,"8.2 based on 7,592 user ratings",2016.0,16+,1.0,0.0,0.0,0.0
6216,TV Show,"Rica, Famosa, Latina",NaN,NaN,United States,2019-04,2016,TV-14,4 Seasons,"International TV Shows, Reality TV, Spanish-La...",5.8 based on 52 user ratings,2014.0,NaN,0.0,1.0,0.0,0.0
6217,TV Show,The Protector,NaN,"Çağatay Ulusoy, Ayça Ayşin Turan, Hazar Ergüçl...",Turkey,2019-04,2019,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...","6.7 based on 30,818 user ratings",2018.0,16+,1.0,0.0,0.0,0.0
6219,TV Show,Liv and Maddie,NaN,"Dove Cameron, Joey Bragg, Tenzing Norgay Train...",United States,2017-04,2017,TV-G,4 Seasons,"Kids' TV, TV Comedies","6.3 based on 6,491 user ratings",2013.0,all,1.0,0.0,0.0,0.0
6221,TV Show,The Cravings,NaN,"Park Hee-bon, Phillip Choi, Hong Wan-pyo, Choi...",South Korea,2017-04,2016,TV-14,2 Seasons,"International TV Shows, Korean TV Shows, TV Co...",7.3 based on 55 user ratings,2017.0,NaN,1.0,0.0,0.0,0.0
6222,TV Show,Star Trek: The Next Generation,NaN,"Patrick Stewart, Jonathan Frakes, LeVar Burton...",United States,2018-04,1993,TV-PG,7 Seasons,"TV Action & Adventure, TV Sci-Fi & Fantasy","8.6 based on 98,930 user ratings",1987.0,7+,1.0,1.0,1.0,0.0
6223,TV Show,Cuckoo,NaN,"Andy Samberg, Taylor Lautner, Greg Davies, Hel...",United Kingdom,2019-04,2019,TV-14,5 Seasons,"British TV Shows, International TV Shows, TV C...","7.3 based on 7,767 user ratings",2012.0,16+,1.0,0.0,0.0,0.0
6225,TV Show,Samantha!,NaN,"Emmanuelle Araújo, Douglas Silva, Sabrina Nona...",Brazil,2019-04,2019,TV-MA,2 Seasons,"International TV Shows, TV Comedies",6.5 based on 454 user ratings,2018.0,7+,1.0,0.0,0.0,0.0
6226,TV Show,Murderous Affairs,NaN,NaN,United States,2018-04,2017,TV-14,3 Seasons,"Crime TV Shows, Docuseries",6.6 based on 192 user ratings,2016.0,16+,1.0,0.0,0.0,0.0
6227,TV Show,Lost Girl,NaN,"Anna Silk, Kris Holden-Ried, Ksenia Solo, Rich...",Canada,2016-04,2015,TV-14,5 Seasons,"TV Dramas, TV Horror, TV Mysteries","7.7 based on 28,386 user ratings",2010.0,16+,1.0,0.0,0.0,0.0
6228,TV Show,Mr. Young,NaN,"Brendan Meyer, Matreya Fedor, Gig Morton, Kurt...",Canada,2019-04,2013,TV-G,2 Seasons,"Kids' TV, TV Comedies","6.1 based on 1,182 user ratings",2011.0,all,1.0,0.0,0.0,0.0
6229,TV Show,Psiconautas,NaN,"Guillermo Toledo, Gabriel Goity, Florencia Peñ...",Argentina,2018-04,2016,TV-MA,2 Seasons,"International TV Shows, Spanish-Language TV Sh...","7.3 based on 2,043 user ratings",2015.0,NaN,1.0,0.0,0.0,0.0
6233,TV Show,Chelsea,NaN,NaN,United States,2017-04,2017,TV-MA,2 Seasons,"Stand-Up Comedy & Talk Shows, TV Comedies",Not Found,2016.0,18+,1.0,0.0,0.0,0.0
6234,TV Show,Crazy Ex-Girlfriend,NaN,"Rachel Bloom, Vincent Rodriguez III, Santino F...",United States,2019-04,2019,TV-14,4 Seasons,"Romantic TV Shows, TV Comedies","7.8 based on 16,510 user ratings",2015.0,16+,1.0,0.0,0.0,0.0
6235,TV Show,The Magic School Bus Rides Again,NaN,"Kate McKinnon, Miles Koseleci-Vieira, Mikaela ...",United States,2018-04,2018,TV-Y,2 Seasons,Kids' TV,6.2 based on 622 user ratings,2017.0,all,1.0,0.0,0.0,0.0
6236,TV Show,New Girl,NaN,"Zooey Deschanel, Jake Johnson, Max Greenfield,...",United States,2019-04,2017,TV-14,7 Seasons,"Romantic TV Shows, TV Comedies","7.7 based on 187,069 user ratings",2011.0,16+,1.0,0.0,0.0,0.0
6237,TV Show,Talking Tom and Friends,NaN,"Colin Hanks, Tom Kenny, James Adomian, Lisa Sc...","Cyprus, Austria, Thailand",2019-04,2017,TV-G,2 Seasons,"Kids' TV, TV Comedies",6.1 based on 244 user ratings,2014.0,all,1.0,0.0,0.0,0.0
6239,TV Show,Justin Time,NaN,"Gage Munroe, Scott McCord, Jenna Warren",Canada,2016-04,2012,TV-Y,2 Seasons,Kids' TV,6.8 based on 172 user ratings,2011.0,all,1.0,0.0,0.0,0.0
6240,TV Show,Terrace House: Boys & Girls in the City,NaN,"You, Reina Triendl, Ryota Yamasato, Yoshimi To...",Japan,2016-04,2016,TV-14,2 Seasons,"International TV Shows, Reality TV","8.2 based on 1,359 user ratings",2015.0,7+,1.0,0.0,0.0,0.0
6241,TV Show,Weeds,NaN,"Mary-Louise Parker, Hunter Parrish, Alexander ...",United States,2014-04,2012,TV-MA,8 Seasons,"TV Comedies, TV Dramas","7.9 based on 101,678 user ratings",2005.0,18+,1.0,0.0,0.0,0.0
6242,TV Show,Gunslinger Girl,NaN,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaN,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","7.4 based on 2,065 user ratings",2003.0,16+,1.0,0.0,0.0,0.0
6244,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies","8.0 based on 72,555 user ratings",1993.0,7+,0.0,1.0,0.0,0.0
6247,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,TV-Y,2 Seasons,Kids' TV,7.5 based on 703 user ratings,2004.0,all,1.0,0.0,0.0,0.0
6248,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","8.3 based on 8,840 user ratings",2003.0,NaN,1.0,0.0,0.0,0.0
6252,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies","8.9 based on 802,016 user ratings",1971.0,18+,0.0,0.0,1.0,0.0

In [122]:
netflix_test_merge.isnull().sum()

type               0
title              0
director        1986
cast             571
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0
IMDB_rating        0
year            2191
age             3992
Netflix         2191
Hulu            2191
Prime Video     2191
Disney+         2191
dtype: int64

### Test RegEx IMDb

In [144]:
netflix_imdb_regex = netflix

In [151]:
netflix_imdb_regex.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,IMDb_rating
0,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019-09,2019,TV-PG,90 min,"Children & Family Movies, Comedies",3.2 based on 294 user ratings
1,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,2016-09,2016,TV-MA,94 min,Stand-Up Comedy,5.0 based on 21 user ratings
2,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2018-09,2013,TV-Y7-FV,1 Season,Kids' TV,"7.9 based on 5,331 user ratings"
3,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2018-09,2016,TV-Y7,1 Season,Kids' TV,6.0 based on 830 user ratings
4,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017-09,2017,TV-14,99 min,Comedies,"5.2 based on 5,496 user ratings"

In [152]:
re.findall(r"\d{1}\.", netflix_imdb_regex["IMDb_rating"])

TypeError: expected string or bytes-like object